### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by padok** [postrational/rest_api_demo#8]
Hello,
I wanted to run your sample code, but apparently I can't import the root packet. 

```
louis@Idris:~/git/rest_api_demo/rest_api_demo$ python3 app.py 
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from rest_api_demo import settings
ModuleNotFoundError: No module named 'rest_api_demo'

```

**Comment by postrational** [comment]
Try to add the parent of `rest_api_demo` to your `PYTHONPATH`
So if you have `rest_api_demo` in `/path/to/parent/rest_api_demo` set `PYTHONPATH` like this:
```
export PYTHONPATH=/path/to/parent:$PYTHONPATH
```

**Comment by padok** [comment]
Thank you, I set the path the wrong way. Now it works.
